### ISSUE TITLE
Checkout session is unreliable in GraphQl. 

### ISSUE THREAD

**Issue by Hexmage** [MultiSafepay/magento2-graphql#3]
https://github.com/MultiSafepay/magento2-graphql/blob/f258524183e96aa6e793a0608867675f97954480/Model/Resolver/PaymentUrl.php#L84

The checkout session isn't always reliably set through graphql, because the frontend doesn't use the magento session directly. This may cause another session to be read accidentally.

**Comment by Hexmage** [comment]
The order_number might already by available in the $value param

**Comment by vinodsowdagar** [comment]
Hi @Hexmage ,

This one slipped away unfortunately, but thank you for the suggestion.
I have created a backlog ticket for this to investigate it further.

When i have an update regarding this, i will keep you informed.

**Comment by danielcivit** [comment]
Hi @Hexmage .

I think this issue could be considered fixed in our recently released new version 3.2.0. 

Now the order is being retrieved from the order_number, already available in the $value param; like you suggested:
https://github.com/MultiSafepay/magento2-graphql/blob/master/Model/Resolver/PaymentUrl.php#L94

Thanks for your feedback. If you still have any issue or feedback, feel free to get back to us, or re-open this issue.
